### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by phantasmicmeans** [rsocket/rsocket#298] opened 2020-03-02 15:11 UTC
Safari browser works fine..
but **chrome** cannot connect to http://rsocket.io 

- Chrome version: 79.0.3945.130

## detail 

```
NET::ERR_CERT_COMMON_NAME_INVALID

Subject: *.github.com

Issuer: DigiCert SHA2 High Assurance Server CA

Expires on: 2020. 4. 7.

Current date: 2020. 3. 3.

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIHZTCCBk2gAwIBAgIQCZdSNOgyQkmb9dELcsqVHjANBgkqhkiG9w0BAQsFADBw
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3...
```

**The website uses HSTS, so can't visit rsocket.io right now. Network errors and attacks are usually temporary, so this page can work later.**

is there any issue on cert?

**Comment by flyinprogrammer** [comment] 2020-03-02 15:42
this is effectively a duplicate of https://github.com/rsocket/rsocket-website/issues/16 - i will post more updates there.

**Closed** 2020-03-02 17:37 UTC
Labels: duplicate

**Comment by aiyagari** [comment] 2020-03-18 09:20
The duplicated bug is also closed, so how can this ever get fixed?  Chrome 80.0.3987.132 still cannot visit the site, and neither can Firefox 68.5.0esr.  Who exactly *can* visit your website?

**Comment by OlegDokuka** [comment] 2020-03-18 09:23
Indeed. Let me reopen the bug in rsocket-website

**Comment by phantasmicmeans** [comment] 2020-03-18 09:27
Still not connected to rsocket.io

**Comment by OlegDokuka** [comment] 2020-03-18 09:52
The webpage is accessible from all of the devices except macbook chrome browser. I'm afraid that can be DNS caches or chrome bug. Nopanic. This will be investigated 🙏

**Comment by phantasmicmeans** [comment] 2020-03-18 15:44
Unfortunately, it is not accessible even on Android 9 :)
